services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.venv

networks:
  app-network:
    driver: bridge
