# Generated by Django 5.2.4 on 2025-07-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='alertthreshold',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
    ]
